export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';

export const GET_ROLES = 'GET_ROLES';
export const CREATE_ROLE = 'CREATE_ROLE';

export const GET_ARTICLES = 'GET_ARTICLES';
export const CREATE_ARTICLE = 'CREATE_ARTICLE';
export const UPDATE_ARTICLE = 'UPDATE_ARTICLE';
export const DESTROY_ARTICLE = 'DESTROY_ARTICLE';
export const ARTICLES_ERROR = 'ARTICLES_ERROR';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DESTROY_PRODUCT = 'DESTROY_PRODUCT';
export const PRODUCT_ERROR = 'PRODUCT_ERROR';
export const GET_PRODUCT = 'GET_PRODUCT';
export const FILTER_PRODUCT = 'FILTER_PRODUCT';
export const FILTER_BY_PRICE = 'FILTER_BY_PRICE';

export const GET_CART = 'GET_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
export const GET_CART_PRODUCTS = 'GET_CART_PRODUCTS';
export const GET_CART_COUNT = 'GET_CART_COUNT';
export const UPDATE_QTY = 'UPDATE_QTY';
export const REMOVE_ITEM = 'REMOVE_ITEM';

export const UPDATE_USER = 'UPDATE_USER';
export const DESTROY_USER = 'DESTROY_USER';

export const GET_USERS = 'GET_USERS';
export const USER_UPDATED = 'USER_UPDATED';

export const GET_EMPLOYEES = 'GET_EMPLOYEES';
export const EMPLOYEE_UPDATED = 'EMPLOYEE_UPDATED';
